### PR TITLE
Adding support for laravel 10

### PR DESCRIPTION
**Pull request by wadday**

### CODE REVIEW

**Comment by ju5t** [comment]
This is a duplicate of #72.

**Comment by Kakad3v** [comment]
Hi @ArielMejiaDev, any luck with the upgrade to laravel 10 ?

**Comment by ArielMejiaDev** [comment]
It has been updated, sorry for the delay.

**Comment by ArielMejiaDev** [comment]
@wadday @ju5t @Kakad3v It has been updated, sorry for the delay.

**Pull request closed without merging**
