### PR TITLE
Add possibility to customize theme

### PR DESCRIPTION
**Pull request by Tschucki**
Currently there is no possibility to change the theme. With this you can at least switch between the light and dark mode.

### CODE REVIEW

**Comment by Tschucki** [comment]
@ArielMejiaDev

**Comment by ArielMejiaDev** [comment]
Thanks!

**Comment by chimit** [comment]
It doesn't work for me. @Tschucki are you sure [constructor should return `$this`](https://github.com/ArielMejiaDev/larapex-charts/pull/54/files#diff-8d072b55ca52128799ee57e976243325e0d9593f0932ec2615cc2fc5ff5f67cfR65)?

**Comment by Tschucki** [comment]
> It doesn't work for me. @Tschucki are you sure [constructor should return `$this`](https://github.com/ArielMejiaDev/larapex-charts/pull/54/files#diff-8d072b55ca52128799ee57e976243325e0d9593f0932ec2615cc2fc5ff5f67cfR65)?

Well. It worked for me 2 years ago. Maybe something has changed.

**Comment by neochaner** [comment]
Changing the theme doesn't work for me.

To fix this you must add the option parameter to the config 
https://github.com/ArielMejiaDev/larapex-charts/blob/master/stubs/resources/views/chart/script.blade.php
 theme: {
            mode: 'dark',
 },

**Comment by neochaner** [comment]
> > It doesn't work for me. @Tschucki are you sure [constructor should return `$this`](https://github.com/ArielMejiaDev/larapex-charts/pull/54/files#diff-8d072b55ca52128799ee57e976243325e0d9593f0932ec2615cc2fc5ff5f67cfR65)?
> 
> Well. It worked for me 2 years ago. Maybe something has changed.

You're probably now using Vue or another rendering method.

**Pull request merged**
