### PR TITLE
Adding support to Laravel 10.x

### PR DESCRIPTION
**Pull request by Mig0o0**

### CODE REVIEW

**Comment by rgbaman** [comment]
Can we get this merged?

**Review by rgbaman — APPROVED** [review]

**Comment by reza-shafee** [comment]
Why is not merge?????????

**Comment by reza-shafee** [comment]
@ArielMejiaDev

**Review by MuriloChianfa — APPROVED** [review]
Please accept them

**Comment by ArielMejiaDev** [comment]
@MuriloChianfa, @reza-shafee, @rgbaman, @Mig0o0, @ju5t   It has been updated, sorry for the delay.

**Pull request closed without merging**
